<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Academico\ActaCalificacionesController;
use App\Http\Controllers\Academico\AsistenteIaController;
use App\Http\Controllers\Academico\AlertaBajaDefinitivaController;
use App\Http\Controllers\Academico\AlertaCorteCapturaController;
use App\Http\Controllers\Academico\AlertaRiesgoAcademicoController;
use App\Http\Controllers\Academico\AlertaInasistenciaController;
use App\Http\Controllers\Academico\AlumnoController;
use App\Http\Controllers\Academico\AsignacionDocenteController;
use App\Http\Controllers\Academico\AsignacionTutoriaController;
use App\Http\Controllers\Academico\AulaController;
use App\Http\Controllers\Academico\AusentismoSindicalController;
use App\Http\Controllers\Academico\BuilderHorarioController;
use App\Http\Controllers\Academico\BuscarDisponibilidadController;
use App\Http\Controllers\Academico\CalificacionController;
use App\Http\Controllers\Academico\CargaAcademicaController;
use App\Http\Controllers\Academico\CargaEstadoController;
use App\Http\Controllers\Academico\CierreDeCursoController;
use App\Http\Controllers\Academico\ConcentradoHorarioController;
use App\Http\Controllers\Academico\ConcursoOposicionController;
use App\Http\Controllers\Academico\ConfiguracionEvaluacionController;
use App\Http\Controllers\Academico\ConvalidacionController;
use App\Http\Controllers\Academico\ConvenioMovilidadController;
use App\Http\Controllers\Academico\CorteCapturaController;
use App\Http\Controllers\Academico\CursoVeranoController;
use App\Http\Controllers\Academico\DiaNoLaborableController;
use App\Http\Controllers\Academico\DiagnosticoHorarioController;
use App\Http\Controllers\Academico\DisponibilidadDocenteController;
use App\Http\Controllers\Academico\EducacionDistanciaController;
use App\Http\Controllers\Academico\EgresadoController;
use App\Http\Controllers\Academico\EquivalenciaController;
use App\Http\Controllers\Academico\EspecialidadController;
use App\Http\Controllers\Academico\FichaDocenteController;
use App\Http\Controllers\Academico\FichaSindicalController;
use App\Http\Controllers\Academico\FuncionPersonalController;
use App\Http\Controllers\Academico\GrupoController;
use App\Http\Controllers\Academico\HorarioController;
use App\Http\Controllers\Academico\HorarioTrabajoController;
use App\Http\Controllers\Academico\IndicadoresAsistenciaController;
use App\Http\Controllers\Academico\GamificacionController;
use App\Http\Controllers\Academico\IncidenciaClaseController;
use App\Http\Controllers\Academico\PasaporteDocenteController;
use App\Http\Controllers\Academico\TorreControlController;
use App\Http\Controllers\Academico\IndicadoresTutoriaController;
use App\Http\Controllers\Academico\InformeSindicalController;
use App\Http\Controllers\Academico\InscripcionDistanciaController;
use App\Http\Controllers\Academico\InstrumentacionDidacticaController;
use App\Http\Controllers\Academico\MallaCurricularController;
use App\Http\Controllers\Academico\MateriaController;
use App\Http\Controllers\Academico\MovilidadEstudiantilController;
use App\Http\Controllers\Academico\PermisoSindicalController;
use App\Http\Controllers\Academico\PlanAccionTutorialController;
use App\Http\Controllers\Academico\PlaneacionDocenteController;
use App\Http\Controllers\Academico\PlantillaSindicalController;
use App\Http\Controllers\Academico\PlazaController;
use App\Http\Controllers\Academico\PrecargaController;
use App\Http\Controllers\Academico\ProgramaDistanciaController;
use App\Http\Controllers\Academico\ReporteAcreditacionController;
use App\Http\Controllers\Academico\ReporteDirectivoController;
use App\Http\Controllers\Academico\SesionClaseController;
use App\Http\Controllers\Academico\SesionTutoriaController;
use App\Http\Controllers\Academico\TrasladoController;
use App\Http\Controllers\Academico\TutoriaController;

// Rutas del modulo Academico - extraidas de routes/api.php.
// Se registran dentro del grupo auth:sanctum en routes/api.php via require.

    Route::get('/alumnos',                                   [AlumnoController::class, 'index']);
    Route::get('/alumnos/{alumno}',                          [AlumnoController::class, 'show']);
    Route::patch('/alumnos/{alumno}',                        [AlumnoController::class, 'update']);
    Route::get('/alumnos/{alumno}/autorizacion-expediente',  [AlumnoController::class, 'autorizacionExpediente']);
    Route::patch('/alumnos/{alumno}/autorizacion-expediente',[AlumnoController::class, 'actualizarAutorizacion']);
    Route::get('/libro-registro-nc/data',                                     [AlumnoController::class, 'libroRegistroNc']);
    Route::get('/materias',                              [MateriaController::class, 'index']);
    Route::post('/materias',                             [MateriaController::class, 'store']);
    Route::get('/materias/{materia}',                    [MateriaController::class, 'show']);
    Route::patch('/materias/{materia}',                  [MateriaController::class, 'update']);
    Route::delete('/materias/{materia}',                 [MateriaController::class, 'destroy']);
    Route::post('/materias/{materia}/documento',         [MateriaController::class, 'subirDocumento']);
    Route::delete('/materias/{materia}/documento',       [MateriaController::class, 'eliminarDocumento']);
    Route::get('/grupos',                                           [GrupoController::class, 'index']);
    Route::post('/grupos',                                          [GrupoController::class, 'store']);
    Route::post('/grupos/liberar-horarios-bulk',                    [GrupoController::class, 'liberarHorariosBulk']);
    Route::post('/grupos/horarios-dias-bulk',                       [GrupoController::class, 'aplicarHorariosDiasBulk']);
    Route::get('/grupos/{grupo}',                                   [GrupoController::class, 'show']);
    Route::patch('/grupos/{grupo}',                                 [GrupoController::class, 'update']);
    Route::delete('/grupos/{grupo}',                                [GrupoController::class, 'destroy']);
    Route::patch('/grupos/{grupo}/liberar-horarios',                [GrupoController::class, 'liberarHorarios']);
    Route::post('/grupos/{grupo}/alumnos',                          [GrupoController::class, 'asignarAlumnos']);
    Route::delete('/grupos/{grupo}/alumnos/{alumno}',               [GrupoController::class, 'quitarAlumno']);
    Route::get('/cargas-academicas',                               [CargaAcademicaController::class, 'index']);
    Route::post('/cargas-academicas',                              [CargaAcademicaController::class, 'store']);
    Route::patch('/cargas-academicas/{cargaAcademica}',            [CargaAcademicaController::class, 'update']);
    Route::delete('/cargas-academicas/{cargaAcademica}',           [CargaAcademicaController::class, 'destroy']);
    Route::get('/admin/docentes',                                  [CargaAcademicaController::class, 'docentes']);
    Route::get('/docentes/fichas',                                 [FichaDocenteController::class, 'index']);
    Route::post('/docentes/fichas',                                [FichaDocenteController::class, 'store']);
    Route::patch('/docentes/{docente}/ficha',                      [FichaDocenteController::class, 'update']);
    Route::get('/mi-ficha-docente',                                [FichaDocenteController::class, 'miFicha']);
    Route::put('/mi-ficha-docente',                                [FichaDocenteController::class, 'actualizarMiCv']);
    Route::get('/tutorias',                    [TutoriaController::class, 'index']);
    Route::post('/tutorias',                   [TutoriaController::class, 'store']);
    Route::post('/tutorias/masivo',            [TutoriaController::class, 'masivo']);
    Route::delete('/tutorias/{tutoria}',       [TutoriaController::class, 'destroy']);
    Route::get('/funciones-personal',                              [FuncionPersonalController::class, 'index']);
    Route::post('/funciones-personal',                             [FuncionPersonalController::class, 'store']);
    Route::patch('/funciones-personal/{funcionPersonal}',          [FuncionPersonalController::class, 'update']);
    Route::delete('/funciones-personal/{funcionPersonal}',         [FuncionPersonalController::class, 'destroy']);
    Route::get('/mallas-curriculares',                             [MallaCurricularController::class, 'index']);
    Route::post('/mallas-curriculares',                            [MallaCurricularController::class, 'store']);
    Route::patch('/mallas-curriculares/{mallaCurricular}',         [MallaCurricularController::class, 'update']);
    Route::delete('/mallas-curriculares/{mallaCurricular}',        [MallaCurricularController::class, 'destroy']);
    Route::get('/aulas',                                           [AulaController::class, 'index']);
    Route::get('/aulas/disponibles',                               [AulaController::class, 'disponibles']);
    Route::get('/aulas/ocupacion',                                 [AulaController::class, 'ocupacion']);
    Route::get('/aulas/{aula}/horario-actual',                     [AulaController::class, 'horarioActual']);
    Route::get('/aulas/fantasma',                                  [AulaController::class, 'fantasma']);
    Route::get('/aulas/{aula}/sugerencias-reubicacion',            [AulaController::class, 'sugerenciasReubicacion']);

    // Índice de salud del semestre por carrera
    Route::get('/salud-semestral',                                 [\App\Http\Controllers\Academico\SaludSemestralController::class, 'index']);

    // Modo día de examen — verificación reforzada de check-in para una fecha puntual
    Route::get('/modos-examen',                                    [\App\Http\Controllers\Academico\ModoExamenController::class, 'index']);
    Route::post('/modos-examen',                                   [\App\Http\Controllers\Academico\ModoExamenController::class, 'activar']);
    Route::delete('/modos-examen/{modoExamen}',                    [\App\Http\Controllers\Academico\ModoExamenController::class, 'desactivar']);
    Route::post('/aulas',                                          [AulaController::class, 'store']);
    Route::patch('/aulas/{aula}',                                  [AulaController::class, 'update']);
    Route::delete('/aulas/{aula}',                                 [AulaController::class, 'destroy']);
    Route::get('/horarios',                                        [HorarioController::class, 'index']);
    Route::get('/horarios/disponibilidad',                         [HorarioController::class, 'disponibilidad']);
    Route::get('/horarios/conflictos',                             [HorarioController::class, 'conflictos']);
    Route::post('/horarios',                                       [HorarioController::class, 'store']);
    Route::patch('/horarios/{horario}',                            [HorarioController::class, 'update']);
    Route::patch('/horarios/{horario}/grupos',                     [HorarioController::class, 'updateGrupos']);
    Route::delete('/horarios/{horario}',                           [HorarioController::class, 'destroy']);
    Route::get('/horarios/builder-grid',                           [BuilderHorarioController::class, 'gridData']);
    Route::post('/horarios/verificar-disponibilidad',              [BuilderHorarioController::class, 'verificar']);
    Route::post('/horarios/asignar',                               [BuilderHorarioController::class, 'asignar']);
    Route::get('/horarios/concentrado',                            [ConcentradoHorarioController::class, 'export']);
    Route::get('/horarios/diagnostico',                            [DiagnosticoHorarioController::class, 'index']);
    Route::post('/horarios/disponibilidad/buscar',                 [BuscarDisponibilidadController::class, 'buscar']);
    Route::get('/disponibilidad-docente',                          [DisponibilidadDocenteController::class, 'index']);
    Route::put('/disponibilidad-docente',                          [DisponibilidadDocenteController::class, 'update']);
    Route::get('/dias-no-laborables',                              [DiaNoLaborableController::class, 'index']);
    Route::post('/dias-no-laborables',                             [DiaNoLaborableController::class, 'store']);
    Route::delete('/dias-no-laborables/{id}',                      [DiaNoLaborableController::class, 'destroy']);
    Route::patch('/cargas-academicas/{carga}/confirmar',           [CargaEstadoController::class, 'confirmar']);
    Route::patch('/cargas-academicas/{carga}/reportar-conflicto',  [CargaEstadoController::class, 'reportarConflicto']);
    Route::get('/horarios-trabajo',                                               [HorarioTrabajoController::class, 'index']);
    Route::get('/horarios-trabajo/mio',                                           [HorarioTrabajoController::class, 'mio']);
    Route::post('/horarios-trabajo',                                              [HorarioTrabajoController::class, 'store']);
    Route::get('/horarios-trabajo/{horarioTrabajo}',                              [HorarioTrabajoController::class, 'show']);
    Route::get('/planeaciones-docentes',                                          [PlaneacionDocenteController::class, 'index']);
    Route::get('/planeaciones-docentes/mias',                                     [PlaneacionDocenteController::class, 'mias']);
    Route::get('/planeaciones-docentes/buscar',                                   [PlaneacionDocenteController::class, 'buscar']);
    Route::get('/planeaciones-docentes/comparar-grupos',                          [PlaneacionDocenteController::class, 'compararGrupos']);
    Route::get('/ia/disponibilidad',                                              [\App\Http\Controllers\Academico\ReglaIaController::class, 'disponibilidad']);
    Route::get('/admin/ia/reglas',                                                [\App\Http\Controllers\Academico\ReglaIaController::class, 'index']);
    Route::put('/admin/ia/reglas',                                                [\App\Http\Controllers\Academico\ReglaIaController::class, 'guardar']);
    Route::delete('/admin/ia/reglas/{regla}',                                     [\App\Http\Controllers\Academico\ReglaIaController::class, 'destroy']);
    Route::post('/ia/mejorar-texto',                                              [AsistenteIaController::class, 'mejorarTexto']);
    Route::get('/planeaciones-docentes/seguimiento',                              [PlaneacionDocenteController::class, 'seguimiento']);
    Route::get('/planeaciones-docentes/seguimiento/pdf',                          [PlaneacionDocenteController::class, 'seguimientoPdf']);
    Route::get('/planeaciones-docentes/acreditacion-por-carrera',                 [PlaneacionDocenteController::class, 'acreditacionPorCarrera']);
    Route::get('/planeaciones-docentes/mi-comparativo',                          [PlaneacionDocenteController::class, 'miComparativo']);
    Route::post('/planeaciones-docentes',                                         [PlaneacionDocenteController::class, 'store']);
    Route::post('/planeaciones-docentes/{planeacionDocente}/enviar',              [PlaneacionDocenteController::class, 'enviar']);
    Route::patch('/planeaciones-docentes/{planeacionDocente}/estatus',            [PlaneacionDocenteController::class, 'cambiarEstatus']);
    Route::patch('/planeaciones-docentes/{planeacionDocente}/dosificacion',       [PlaneacionDocenteController::class, 'actualizarDosificacion']);
    Route::post('/planeaciones-docentes/{planeacionDocente}/clonar',              [PlaneacionDocenteController::class, 'clonar']);
    Route::get('/planeaciones-docentes/{planeacionDocente}/archivo',              [PlaneacionDocenteController::class, 'archivo']);
    Route::get('/planeaciones-docentes/{planeacionDocente}/pdf-calendario',       [PlaneacionDocenteController::class, 'pdfCalendario']);
    Route::get('/planeaciones-docentes/{planeacionDocente}/pdf-instrumentacion',  [PlaneacionDocenteController::class, 'pdfInstrumentacion']);
    Route::get('/planeaciones-docentes/{planeacionDocente}/docx-instrumentacion', [PlaneacionDocenteController::class, 'docxInstrumentacion']);
    Route::get('/planeaciones-docentes/{planeacionDocente}/versiones',            [PlaneacionDocenteController::class, 'versiones']);
    Route::post('/planeaciones-docentes/{planeacionDocente}/versiones/{version}/restaurar', [PlaneacionDocenteController::class, 'restaurarVersion']);
    Route::get('/planeaciones-docentes/{planeacionDocente}/comentarios',          [PlaneacionDocenteController::class, 'comentarios']);
    Route::post('/planeaciones-docentes/{planeacionDocente}/comentarios',         [PlaneacionDocenteController::class, 'agregarComentario']);
    Route::patch('/planeaciones-docentes/{planeacionDocente}/comentarios/resolver', [PlaneacionDocenteController::class, 'resolverComentarios']);
    Route::get('/planeaciones-docentes/{planeacionDocente}/archivos',              [PlaneacionDocenteController::class, 'archivos']);
    Route::post('/planeaciones-docentes/{planeacionDocente}/archivos',             [PlaneacionDocenteController::class, 'subirArchivo']);
    Route::delete('/planeaciones-docentes/{planeacionDocente}/archivos/{archivo}', [PlaneacionDocenteController::class, 'eliminarArchivo']);
    Route::get('/planeaciones-docentes/{planeacionDocente}/archivos/{archivo}/descargar', [PlaneacionDocenteController::class, 'descargarArchivo']);
    Route::get('/planeaciones-docentes/{planeacionDocente}',                     [PlaneacionDocenteController::class, 'show']);
    Route::get('/admin/periodos/{periodo}/cortes-captura',     [CorteCapturaController::class, 'index']);
    Route::post('/admin/periodos/{periodo}/cortes-captura',    [CorteCapturaController::class, 'store']);
    Route::patch('/admin/cortes-captura/{corte}',              [CorteCapturaController::class, 'update']);
    Route::post('/cortes-captura/{corte}/evaluar',              [CorteCapturaController::class, 'evaluar']);
    Route::get('/cortes-captura/{corte}/cumplimiento',           [CorteCapturaController::class, 'cumplimiento']);
    Route::get('/alertas-corte-captura',                        [AlertaCorteCapturaController::class, 'index']);
    Route::patch('/alertas-corte-captura/{alerta}/marcar-leida', [AlertaCorteCapturaController::class, 'marcarLeida']);
    Route::get('/alumno/precarga-academica',                              [PrecargaController::class, 'index']);
    Route::get('/alumno/precarga-academica/pdf',                          [PrecargaController::class, 'pdf']);
    Route::post('/alumno/precarga-academica/selecciones',                 [PrecargaController::class, 'seleccionar']);
    Route::delete('/alumno/precarga-academica/selecciones/{carga_id}',   [PrecargaController::class, 'deseleccionar']);
    Route::post('/configuraciones-evaluacion',                            [ConfiguracionEvaluacionController::class, 'store']);
    Route::get('/configuraciones-evaluacion/{carreraId}',                 [ConfiguracionEvaluacionController::class, 'show']);
    Route::get('/grupos/{grupo}/calificaciones',                          [CalificacionController::class, 'porGrupo']);
    Route::get('/grupos/{grupo}/calificaciones/historial',                [CalificacionController::class, 'historial']);
    Route::get('/grupos/{grupo}/calificaciones/exportar',                 [CalificacionController::class, 'exportarCsv']);
    Route::get('/grupos/{grupo}/calificaciones/acta-pdf',                  [CalificacionController::class, 'actaPdf']);
    Route::get('/grupos/{grupo}/calificaciones/acta-excel',                [CalificacionController::class, 'actaExcel']);
    Route::get('/grupos/{grupo}/calificaciones/acta-estado',               [CalificacionController::class, 'actaEstado']);
    Route::patch('/grupos/{grupo}/calificaciones/acta-pdf/firmar',         [CalificacionController::class, 'actaFirmar']);
    Route::post('/grupos/{grupo}/calificaciones/importar',                [CalificacionController::class, 'importarCsv']);
    Route::get('/grupos/{grupo}/acta-calificaciones/pdf',                 [ActaCalificacionesController::class, 'pdf']);
    Route::patch('/grupos/{grupo}/acta-calificaciones/firmar',            [ActaCalificacionesController::class, 'firmar']);
    Route::post('/calificaciones',                                        [CalificacionController::class, 'store']);
    Route::post('/cierres-de-curso',                                      [CierreDeCursoController::class, 'store']);
    Route::post('/grupos/{grupo}/cierre-de-curso/reabrir',                [CierreDeCursoController::class, 'reabrir']);
    Route::get('/alertas-baja-definitiva',                                [AlertaBajaDefinitivaController::class, 'index']);
    Route::patch('/alertas-baja-definitiva/{alerta}/revisar',             [AlertaBajaDefinitivaController::class, 'revisar']);

    // Alerta temprana de riesgo académico — cruce de reprobación/inasistencia/incidencias
    Route::get('/alertas-riesgo-academico',                              [AlertaRiesgoAcademicoController::class, 'index']);

    // Alerta de deserción temprana — patrón de asistencia de las primeras semanas
    Route::get('/alertas-desercion-temprana',                            [\App\Http\Controllers\Academico\AlertaDesercionTempranaController::class, 'index']);

    // Bitácora de mantenimiento de aulas (generada desde incidencias de prefectura)
    Route::get('/tickets-mantenimiento',                                  [\App\Http\Controllers\Academico\TicketMantenimientoController::class, 'index']);
    Route::patch('/tickets-mantenimiento/{ticketMantenimiento}',          [\App\Http\Controllers\Academico\TicketMantenimientoController::class, 'update']);

    // Torre de control — estado en vivo del campus (ocupación, incidencias, asistencia)
    // Contadores de pendientes del índice de Gestión Académica (una sola petición, en caché)
    Route::get('/gestion-academica/avisos',                               [\App\Http\Controllers\Academico\GestionAcademicaAvisosController::class, 'index']);
    Route::get('/torre-control',                                          [TorreControlController::class, 'index']);

    // Pasaporte QR de cumplimiento del docente
    Route::get('/docentes/{docente}/pasaporte',                           [PasaporteDocenteController::class, 'resumen']);

    // Gamificación — ranking de cumplimiento docente con insignias
    Route::get('/gamificacion/ranking-docentes',                          [GamificacionController::class, 'rankingDocentes']);

    // Llaves de acceso para el feed de exportación BI (Power BI / Looker Studio)
    Route::get('/admin/api-keys',                                         [\App\Http\Controllers\Admin\ApiKeyController::class, 'index']);
    Route::post('/admin/api-keys',                                        [\App\Http\Controllers\Admin\ApiKeyController::class, 'store']);
    Route::patch('/admin/api-keys/{apiKey}/revocar',                      [\App\Http\Controllers\Admin\ApiKeyController::class, 'revocar']);

    // Bitácora de prefectura — incidencias de ronda por aula/grupo
    Route::get('/incidencias-clase',                                      [IncidenciaClaseController::class, 'index']);
    Route::post('/incidencias-clase',                                     [IncidenciaClaseController::class, 'store']);
    Route::get('/incidencias-clase/horario-esperado',                     [IncidenciaClaseController::class, 'horarioEsperado']);
    Route::get('/alumnos/{alumno}/situacion-academica',                   [CalificacionController::class, 'situacionAcademica']);
    Route::get('/alumnos/{alumno}/kardex',                                [CalificacionController::class, 'kardex']);
    Route::get('/asignaciones-docentes',                                 [AsignacionDocenteController::class, 'index']);
    Route::post('/asignaciones-docentes',                                [AsignacionDocenteController::class, 'store']);
    Route::get('/asignaciones-docentes/{carrera_id}',                    [AsignacionDocenteController::class, 'index']);
    Route::patch('/asignaciones-docentes/{asignacionDocente}',           [AsignacionDocenteController::class, 'update']);
    Route::get('/docentes/{docenteId}/carga-horaria',                    [AsignacionDocenteController::class, 'cargaHoraria']);
    Route::get('/especialidades',                                                     [EspecialidadController::class, 'index']);
    Route::post('/especialidades',                                                    [EspecialidadController::class, 'store']);
    Route::patch('/especialidades/{especialidad}',                                    [EspecialidadController::class, 'update']);
    Route::patch('/especialidades/{especialidad}/autorizar',                          [EspecialidadController::class, 'autorizar']);
    Route::get('/especialidades/{especialidad}/oficio/pdf',                           [EspecialidadController::class, 'oficio']);
    Route::get('/programas-educativos/{carrera}/especialidades',                      [EspecialidadController::class, 'porCarrera']);
    Route::post('/solicitudes-apertura-especialidad',                                 [EspecialidadController::class, 'solicitarApertura']);
    Route::patch('/solicitudes-apertura-especialidad/{solicitud}/dictaminar',         [EspecialidadController::class, 'dictaminar']);
    Route::post('/alumnos/{alumno}/especialidad-seleccionada',                        [EspecialidadController::class, 'seleccionar']);
    Route::get('/instrumentaciones-didacticas',                                      [InstrumentacionDidacticaController::class, 'index']);
    Route::post('/instrumentaciones-didacticas',                                     [InstrumentacionDidacticaController::class, 'store']);
    Route::patch('/instrumentaciones-didacticas/{instrumentacionDidactica}',         [InstrumentacionDidacticaController::class, 'update']);
    Route::patch('/instrumentaciones-didacticas/{instrumentacionDidactica}/enviar',  [InstrumentacionDidacticaController::class, 'enviar']);
    Route::patch('/instrumentaciones-didacticas/{instrumentacionDidactica}/revisar-da', [InstrumentacionDidacticaController::class, 'revisarDesarrolloAcademico']);
    Route::patch('/instrumentaciones-didacticas/{instrumentacionDidactica}/liberar', [InstrumentacionDidacticaController::class, 'liberar']);
    Route::patch('/instrumentaciones-didacticas/{instrumentacionDidactica}/visto-bueno',
                                                                                     [InstrumentacionDidacticaController::class, 'vistoBueno']);
    Route::get('/instrumentaciones-didacticas/{instrumentacionDidactica}/pdf',      [InstrumentacionDidacticaController::class, 'pdf']);
    Route::get('/sesiones-clase',                                      [SesionClaseController::class, 'index']);
    Route::post('/sesiones-clase',                                     [SesionClaseController::class, 'store']);
    Route::get('/sesiones-clase/{sesionClase}',                        [SesionClaseController::class, 'show']);
    Route::patch('/sesiones-clase/{sesionClase}/asistencia',           [SesionClaseController::class, 'actualizarAsistencia']);
    Route::get('/grupos/{grupo}/reporte-asistencia',                   [SesionClaseController::class, 'reporteAsistenciaGrupo']);
    Route::get('/alumnos/{alumnoId}/asistencia',                       [SesionClaseController::class, 'asistenciaAlumno']);
    Route::post('/sesiones-clase/{sesionClase}/enviar-resumen',                        [SesionClaseController::class, 'enviarResumenSesion']);
    Route::post('/sesiones-clase/{sesionClase}/generar-checkin',                       [SesionClaseController::class, 'generarCheckin']);
    Route::post('/sesiones-clase/{sesionClase}/checkin',                               [SesionClaseController::class, 'checkin']);
    Route::post('/cargas-academicas/{cargaAcademica}/asistencia/enviar-lista-blanco',  [SesionClaseController::class, 'enviarListaBlanco']);
    Route::post('/cargas-academicas/{cargaAcademica}/asistencia/enviar-reporte',       [SesionClaseController::class, 'enviarReporteGrupo']);
    Route::get('/cargas-academicas/{cargaAcademica}/asistencia/lista-blanco/pdf',      [SesionClaseController::class, 'listaBlancoPdf']);
    Route::get('/cargas-academicas/{cargaAcademica}/asistencia/reporte/pdf',           [SesionClaseController::class, 'reportePdf']);
    Route::get('/cargas-academicas/{cargaAcademica}/asistencia/reporte/excel',         [SesionClaseController::class, 'reporteExcel']);
    Route::post('/admin/asistencias/enviar-masivo',                                    [SesionClaseController::class, 'enviarMasivo']);
    Route::get('/alertas/inasistencias',                               [AlertaInasistenciaController::class, 'index']);
    Route::patch('/alertas/inasistencias/{alerta}/leer',               [AlertaInasistenciaController::class, 'marcarLeida']);
    Route::get('/reportes/carga-academica',                            [SesionClaseController::class, 'reporteCargaAcademica']);
    Route::get('/egresados',                [EgresadoController::class, 'index']);
    Route::post('/egresados',               [EgresadoController::class, 'store']);
    Route::patch('/egresados/{egresado}',   [EgresadoController::class, 'update']);
    Route::get('/reportes/matricula/pdf',             [ReporteDirectivoController::class, 'matriculaPdf']);
    Route::get('/reportes/calificaciones/pdf',        [ReporteDirectivoController::class, 'calificacionesPdf']);
    Route::get('/reportes/directorio/{tipo}/pdf',     [ReporteDirectivoController::class, 'directorioPdf']);
    Route::get('/reportes/acreditacion/pdf',          [ReporteAcreditacionController::class, 'pdf']);
    Route::get('/indicadores/asistencia',                     [IndicadoresAsistenciaController::class, 'dashboard']);
    Route::get('/indicadores/asistencia/carrera/{carreraId}', [IndicadoresAsistenciaController::class, 'porCarrera']);
    Route::get('/asignaciones-tutoria',                        [AsignacionTutoriaController::class, 'index']);
    Route::post('/asignaciones-tutoria',                       [AsignacionTutoriaController::class, 'store']);
    Route::patch('/asignaciones-tutoria/{asignacion}',         [AsignacionTutoriaController::class, 'update']);
    Route::get('/sesiones-tutoria',                            [SesionTutoriaController::class, 'index']);
    Route::post('/sesiones-tutoria',                           [SesionTutoriaController::class, 'store']);
    Route::get('/sesiones-tutoria/{tutorId}',                  [SesionTutoriaController::class, 'porTutor']);
    Route::get('/planes-accion-tutorial',                      [PlanAccionTutorialController::class, 'index']);
    Route::post('/planes-accion-tutorial',                     [PlanAccionTutorialController::class, 'store']);
    Route::patch('/planes-accion-tutorial/{plan}/estatus',     [PlanAccionTutorialController::class, 'updateEstatus']);
    Route::get('/indicadores/tutoria',                         [IndicadoresTutoriaController::class, 'dashboard']);
    Route::get('/traslados',                                   [TrasladoController::class, 'index']);
    Route::post('/traslados',                                  [TrasladoController::class, 'store']);
    Route::patch('/traslados/{traslado}/gestionar',            [TrasladoController::class, 'gestionar']);
    Route::get('/traslados/{traslado}/kardex/pdf',             [TrasladoController::class, 'kardexPdf']);
    Route::get('/convalidaciones',                             [ConvalidacionController::class, 'index']);
    Route::post('/convalidaciones',                            [ConvalidacionController::class, 'store']);
    Route::get('/equivalencias',                               [EquivalenciaController::class, 'index']);
    Route::post('/equivalencias',                              [EquivalenciaController::class, 'store']);
    Route::get('/alumnos/{alumno}/historial-academico',        [AlumnoController::class, 'historialAcademico']);
    Route::get('/convenios-movilidad',                             [ConvenioMovilidadController::class, 'index']);
    Route::post('/convenios-movilidad',                            [ConvenioMovilidadController::class, 'store']);
    Route::get('/movilidad-estudiantil',                           [MovilidadEstudiantilController::class, 'index']);
    Route::post('/movilidad-estudiantil',                          [MovilidadEstudiantilController::class, 'store']);
    Route::patch('/movilidad-estudiantil/{movilidad}/calificaciones', [MovilidadEstudiantilController::class, 'registrarCalificaciones']);
    Route::get('/cursos-verano',                                   [CursoVeranoController::class, 'index']);
    Route::post('/cursos-verano',                                  [CursoVeranoController::class, 'store']);
    Route::post('/cursos-verano/{cursoVerano}/inscripciones',      [CursoVeranoController::class, 'inscribir']);
    Route::patch('/cursos-verano/{cursoVerano}/cerrar',            [CursoVeranoController::class, 'cerrar']);
    Route::get('/programas-distancia',                             [ProgramaDistanciaController::class, 'index']);
    Route::post('/programas-distancia',                            [ProgramaDistanciaController::class, 'store']);
    Route::post('/inscripciones-distancia',                        [InscripcionDistanciaController::class, 'store']);
    Route::get('/alumnos/{alumno}/avance-distancia',               [AlumnoController::class, 'avanceDistancia']);
    Route::get('/seguimiento-distancia',                           [EducacionDistanciaController::class, 'seguimiento']);
    Route::get('/indicadores/distancia',                           [EducacionDistanciaController::class, 'indicadores']);
    Route::get('/docentes/{docente}/ficha-sindical',               [FichaSindicalController::class, 'show']);
    Route::post('/docentes/{docente}/ficha-sindical',              [FichaSindicalController::class, 'store']);
    Route::patch('/docentes/{docente}/ficha-sindical',             [FichaSindicalController::class, 'update']);
    Route::get('/plazas',                                          [PlazaController::class, 'index']);
    Route::post('/plazas/{plaza}/movimientos',                     [PlazaController::class, 'registrarMovimiento']);
    Route::get('/reportes/plantilla-sindical/pdf',                 [PlantillaSindicalController::class, 'pdf']);
    Route::get('/permisos-sindicales',                                     [PermisoSindicalController::class, 'index']);
    Route::post('/permisos-sindicales',                                    [PermisoSindicalController::class, 'store']);
    Route::get('/permisos-sindicales/{permiso}/oficio-pdf',                [PermisoSindicalController::class, 'oficio']);
    Route::get('/docentes/{docente}/historial-escalafon',                  [FichaSindicalController::class, 'historialEscalafon']);
    Route::get('/concursos-oposicion',                                     [ConcursoOposicionController::class, 'index']);
    Route::post('/concursos-oposicion',                                    [ConcursoOposicionController::class, 'store']);
    Route::get('/reportes/permisos-sindicales/{periodo}/pdf',              [InformeSindicalController::class, 'pdf']);
    Route::get('/dashboard/ausentismo-sindical',                           [AusentismoSindicalController::class, 'dashboard']);
